name:                effectiveHaskell

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.11.7

ghc-options:  [ -Wall, -Wcompat, -Widentities, -Wincomplete-record-updates, -Wincomplete-uni-patterns, -Wmissing-home-modules, -Wpartial-fields, -Wredundant-constraints ]

library:
  source-dirs: src

executables:
  effectiveHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N ]
    dependencies:
    - effectiveHaskell

tests:
  effectiveHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N ]
    dependencies:
    - effectiveHaskell
